/** One lexical unit of a generated SQL statement. */
export type SqlToken =
    | { kind: 'word'; value: string }
    | { kind: 'quoted'; value: string }
    | { kind: 'string'; value: string }
    | { kind: 'number'; value: string }
    | { kind: 'param'; index: number }
    | { kind: 'punct'; value: string };

const MULTI_CHAR_OPERATORS = ['<>', '!=', '>=', '<='];

/**
 * Splits a statement generated by `drizzle-orm/pg-proxy` into tokens the
 * statement parser can walk.
 *
 * Bare words are lowercased so keyword matching downstream never has to care
 * about Drizzle's casing, while `"quoted"` identifiers keep their exact text —
 * Postgres treats those as case-sensitive and PostgREST needs them verbatim.
 * Comments and whitespace are dropped; nothing here validates grammar.
 *
 * @param sql The generated statement text, `$n` placeholders included.
 * @returns The token list, in source order.
 */
export default function tokenizeSql(sql: string): SqlToken[] {
    const tokens: SqlToken[] = [];
    let i = 0;

    while (i < sql.length) {
        const char = sql[i]!;

        if (/\s/.test(char)) {
            i++;
            continue;
        }

        if (char === '-' && sql[i + 1] === '-') {
            const end = sql.indexOf('\n', i);
            i = end === -1 ? sql.length : end + 1;
            continue;
        }

        if (char === '/' && sql[i + 1] === '*') {
            const end = sql.indexOf('*/', i + 2);
            i = end === -1 ? sql.length : end + 2;
            continue;
        }

        if (char === '"') {
            const [value, next] = readDelimited(sql, i + 1, '"');
            tokens.push({ kind: 'quoted', value });
            i = next;
            continue;
        }

        if (char === "'") {
            const [value, next] = readDelimited(sql, i + 1, "'");
            tokens.push({ kind: 'string', value });
            i = next;
            continue;
        }

        if (char === '$' && /[0-9]/.test(sql[i + 1] ?? '')) {
            let end = i + 1;
            while (end < sql.length && /[0-9]/.test(sql[end]!)) end++;
            tokens.push({ kind: 'param', index: Number(sql.slice(i + 1, end)) });
            i = end;
            continue;
        }

        if (/[0-9]/.test(char)) {
            let end = i;
            while (end < sql.length && /[0-9.]/.test(sql[end]!)) end++;
            tokens.push({ kind: 'number', value: sql.slice(i, end) });
            i = end;
            continue;
        }

        if (/[A-Za-z_]/.test(char)) {
            let end = i;
            while (end < sql.length && /[A-Za-z0-9_]/.test(sql[end]!)) end++;
            tokens.push({ kind: 'word', value: sql.slice(i, end).toLowerCase() });
            i = end;
            continue;
        }

        const operator = MULTI_CHAR_OPERATORS.find((candidate) => sql.startsWith(candidate, i));
        if (operator) {
            tokens.push({ kind: 'punct', value: operator });
            i += operator.length;
            continue;
        }

        tokens.push({ kind: 'punct', value: char });
        i++;
    }

    return tokens;
}

function readDelimited(sql: string, from: number, delimiter: string): [string, number] {
    let value = '';
    let i = from;
    while (i < sql.length) {
        if (sql[i] === delimiter) {
            if (sql[i + 1] === delimiter) {
                value += delimiter;
                i += 2;
                continue;
            }
            return [value, i + 1];
        }
        value += sql[i];
        i++;
    }
    return [value, sql.length];
}
