coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%

ignore:
  - "package/src/general/general_functions.ts"
  - "package/src/config/middleware.ts"
