-- Executes a statement generated by cloudflare-next-intl's `db` module and
-- returns its rows as positional JSON arrays, which is the shape
-- drizzle-orm/pg-proxy maps result columns from.
--
-- SECURITY INVOKER is load-bearing: the statement runs with the privileges of
-- the caller (anon or authenticated, per the request's JWT), so row-level
-- security still applies exactly as it does over the REST API. Do not change
-- this to SECURITY DEFINER, and do not add a role parameter — either would
-- turn this into a privilege-escalation primitive.
create or replace function public.cfni_exec(statement text, params jsonb default '[]'::jsonb)
returns json
language plpgsql
security invoker
as $$
declare
    result json;
    args text[];
begin
    select coalesce(array_agg(value #>> '{}' order by ordinality), '{}')
      into args
      from jsonb_array_elements(params) with ordinality as t(value, ordinality);

    execute format('select coalesce(json_agg(json_build_array(r.*)), ''[]''::json) from (%s) r', statement)
       into result
      using args;

    return result;
end;
$$;

revoke all on function public.cfni_exec(text, jsonb) from public;
grant execute on function public.cfni_exec(text, jsonb) to authenticated;
-- Grant to anon only if your app calls withPublicDb:
grant execute on function public.cfni_exec(text, jsonb) to anon;
