-- Executes a statement generated by cloudflare-next-intl's `db` module and
-- returns its rows/rowCount as jsonb, in the shape drizzle-orm/pg-proxy expects.
--
-- v2: statements arrive with parameters already inlined as literals by the
-- `db` transport (see `inline_params.ts`), so this function takes no
-- parameters and never binds anything itself. It also now supports
-- INSERT/UPDATE/DELETE, with or without RETURNING.
--
-- Each output row is cast with `r::text`, Postgres' own composite-literal
-- text format: `(field1,field2,...)`, fields comma-separated, quoted with
-- `"…"` (doubling embedded quotes) whenever a field's own text contains a
-- comma/quote/paren/backslash/whitespace, and empty-unquoted for NULL. Every
-- field is already in that column's normal `::text` form — arrays as
-- `{1,2}`, booleans as `t`/`f`, timestamps without a `T`, full `numeric`
-- precision — the same representation the `pg` wire protocol sends in text
-- mode, and what Drizzle's column mappers decode. Unlike `row_to_json`/
-- `hstore(record)`, this stays correct with duplicate column names (a common
-- shape after a join with `select a.*, b.*`), since it is purely positional
-- and never keys fields by name. The transport (`supabase_transport.ts`)
-- parses this literal back into a positional array with `parse_composite.ts`.
--
-- SECURITY INVOKER is load-bearing: the statement runs with the privileges of
-- the caller (anon or authenticated, per the request's JWT), so row-level
-- security still applies exactly as it does over the REST API. Do not change
-- this to SECURITY DEFINER, and do not add a role parameter — either would
-- turn this into a privilege-escalation primitive.
--
-- The drop below is only needed when upgrading from the old `json`-returning
-- v1 of this function — `create or replace` cannot change a function's
-- return type, and is a no-op (safe to re-run) when this is a fresh install.
drop function if exists public.cfni_exec(text);

create or replace function public.cfni_exec(statement text)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
    top_level_verb text;
    has_returning boolean;
    has_inner_writable_cte boolean;
    rows_json jsonb := '[]'::jsonb;
    row_count bigint := 0;
    row_value record;
    row_texts text[] := '{}';
begin
    top_level_verb := public.cfni_top_level_verb(statement);
    has_returning := statement ~* '\yreturning\y';

    if top_level_verb in ('insert', 'update', 'delete') and not has_returning then
        execute statement;
        get diagnostics row_count = row_count;
        return jsonb_build_object('rows', '[]'::jsonb, 'rowCount', row_count);
    end if;

    if top_level_verb in ('insert', 'update', 'delete') then
        -- INSERT/UPDATE/DELETE with RETURNING cannot be wrapped as
        -- `from (<stmt>) r` — Postgres rejects DML directly inside FROM —
        -- so run it as a CTE instead and select its rows out of that.
        execute format(
            'with cfni_dml_result as (%s) select coalesce(jsonb_agg(r::text), ''[]''::jsonb), count(*) from cfni_dml_result r',
            statement
        ) into rows_json, row_count;
        return jsonb_build_object('rows', rows_json, 'rowCount', row_count);
    end if;

    -- Top-level statement is a SELECT (plain, or `with ... select ...`).
    has_inner_writable_cte := statement ~* '\y(with|,)\s+[A-Za-z_][A-Za-z0-9_]*\s+as\s*\(\s*(insert|update|delete)\y';
    if has_inner_writable_cte then
        -- Postgres forbids nesting a WITH that contains a data-modifying
        -- statement inside another query (`from (with u as (update ...
        -- returning ...) select ... from u) r` is rejected even though the
        -- statement is legal standalone) — so this shape must run exactly
        -- as given, not wrapped in a further subquery. Row values are
        -- collected by iterating the statement's own result set instead,
        -- casting each row to its composite-literal text form directly.
        for row_value in execute statement loop
            row_texts := row_texts || (row_value::text);
            row_count := row_count + 1;
        end loop;
        return jsonb_build_object('rows', to_jsonb(row_texts), 'rowCount', row_count);
    end if;

    -- Plain SELECT with no inner writable CTE: wrap as a subquery and emit
    -- each row's composite-literal text form; the transport parses it back
    -- into a positional array of column values.
    execute format(
        'select coalesce(jsonb_agg(r::text), ''[]''::jsonb), count(*) from (%s) r',
        statement
    ) into rows_json, row_count;

    return jsonb_build_object('rows', rows_json, 'rowCount', row_count);
end;
$$;

-- Finds the leading keyword of a statement's *outermost* clause, skipping
-- past any leading CTE chain (`with x as (...), y as (...) <verb> ...`) by
-- tracking paren depth rather than a single non-greedy regex match, which
-- breaks on multiple CTEs or parens nested inside a CTE body. Returns one of
-- 'select', 'insert', 'update', 'delete', or 'other' (lowercased).
create or replace function public.cfni_top_level_verb(statement text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare
    stripped text;
    depth int := 0;
    i int := 1;
    len int;
    ch text;
begin
    stripped := regexp_replace(statement, '^(\s*--[^\n]*\n|\s*/\*.*?\*/)*\s*', '', 'sn');

    if stripped !~* '^with\y' then
        return lower((regexp_match(stripped, '^([A-Za-z]+)'))[1]);
    end if;

    len := length(stripped);
    while i <= len loop
        ch := substr(stripped, i, 1);
        if ch = '(' then
            depth := depth + 1;
        elsif ch = ')' then
            depth := depth - 1;
        elsif depth = 0 and ch = ',' then
            -- Between CTE definitions at depth 0; keep scanning for the
            -- statement that follows the whole `with ... ,` chain.
            null;
        elsif depth = 0 and substr(stripped, i) ~* '^(select|insert|update|delete)\y' then
            return lower((regexp_match(substr(stripped, i), '^([A-Za-z]+)'))[1]);
        end if;
        i := i + 1;
    end loop;

    return 'other';
end;
$$;

-- Runs several statements as one atomic unit: `execute`d one at a time via
-- `cfni_exec`, all inside this single function body, so a failure on any
-- statement rolls back everything the batch already did — a plpgsql function
-- call is itself an implicit transaction, which is what makes this atomic
-- even though `pg-proxy` (the Supabase-mode transport) can open no
-- transaction of its own: each statement it sends is normally its own
-- independent PostgREST round-trip with no shared session. This is the
-- explicit batch API for that gap — see `withUserTransaction`/
-- `withPublicTransaction` on the TypeScript side, which render every query
-- in the callback with `.toSQL()` up front (nothing executes until the
-- batch is sent) and pass the resulting array here as one call.
--
-- Returns a jsonb array with one `cfni_exec`-shaped `{rows, rowCount}` result
-- per input statement, in the same order — so the caller can read each
-- statement's own result the way it would outside a batch.
--
-- SECURITY INVOKER for the same reason as `cfni_exec`: the whole batch runs
-- with the caller's own privileges, so RLS applies per statement exactly as
-- it would if each ran on its own.
create or replace function public.cfni_exec_batch(statements text[])
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
    results jsonb := '[]'::jsonb;
    statement text;
begin
    foreach statement in array statements loop
        results := results || jsonb_build_array(public.cfni_exec(statement));
    end loop;
    return results;
end;
$$;

revoke all on function public.cfni_exec(text) from public;
grant execute on function public.cfni_exec(text) to authenticated;
-- Grant to anon only if your app calls withPublicDb:
grant execute on function public.cfni_exec(text) to anon;
grant execute on function public.cfni_exec(text) to service_role;

revoke all on function public.cfni_exec_batch(text[]) from public;
grant execute on function public.cfni_exec_batch(text[]) to authenticated;
grant execute on function public.cfni_exec_batch(text[]) to anon;
grant execute on function public.cfni_exec_batch(text[]) to service_role;

revoke all on function public.cfni_top_level_verb(text) from public;
grant execute on function public.cfni_top_level_verb(text) to authenticated;
grant execute on function public.cfni_top_level_verb(text) to anon;
grant execute on function public.cfni_top_level_verb(text) to service_role;
