name: Push Code Coverage

on:
  workflow_dispatch:
  push:
    paths:
      - "package/**"
    branches:
      - main

concurrency:
  group: generate-code-coverage
  cancel-in-progress: true

jobs:
  push_code_coverage:
    uses: demian-ilnytskyi/workflows/.github/workflows/package_push_code_coverage.yml@main
    secrets: inherit
    with:
      project_type: nextjs
      working_directory: package
      test_path: src
      min_coverage: 100
